### ISSUE TITLE
send_command service - add protocols

### ISSUE THREAD

**Issue by crazymikefra** [crazymikefra/HA_RFPlayerNext#4]
`Pour AC : Je ne trouve pas trace de ce protocole dans la doc. C'est bien un protocole ou une fonctionnalité ?`
Il est vrai que fait partie de CHACON DIO les versions en 433

Le Jamming c'était le bord.. à implémenté de toute façon. Je vais voir si je peux te le modifier en préparation.

Un truc il faut que tu ajoutes la possibilité de mettre "" dans service yaml et EDISIOFRAME. [sinon on passe en mode yaml modifié dans développement]
 ```       
      selector:
        select:
          options:
              - ""
              - "X10"
              - "VISONIC"
              - "BLYSS"
              - "CHACON"
              - "OREGON"
              - "DOMIA"
              - "OWL"
              - "X2D"
              - "RTS"
              - "KD101"
              - "PARROT"
              - "TIC"
              - "FS20"
              - "JAMMING"
              - "EDISIO"
              - "EDISIOFRAME"
          mode: dropdown
```

_Originally posted by @Doubledom45 in https://github.com/crazymikefra/HA_RFPlayerNext/discussions/3#discussioncomment-5115507_
